### ISSUE TITLE
about train_list.txt

### ISSUE THREAD

**Issue by SangMyeongWoh** [mx-mark/VideoTransformer-pytorch#4] opened 2022-02-23 09:02 UTC
I just testing this repo for video detection

Can i have annotation files??

**Comment by hillaric** [comment] 2022-03-01 08:49
Do you know the format of train_file.txt, I find it contains video_dir and label. Hope useful for you.

**Comment by aries-young** [comment] 2022-03-18 05:24
Do you know the format of train_file.txt, I find it contains video_dir and label. Hope useful for you.
Duplicate of #

**Closed** 2022-04-01 01:21 UTC
